version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: erikaheidi/hacktober-board
    container_name: hacktober-app
    restart: unless-stopped
    working_dir: /var/www/
    # Override the default command, adding an init script before it
    command: bash -c "docker-compose/app/app-init.sh && php-fpm"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    volumes:
      # Mount the entire codebase, minus paths in .dockerignore
      - ./:/var/www
      # Mount empty volume to the image's vendor directory so we don't overwrite it
      - empty:/var/www/vendor
    networks:
      - hacktober
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    container_name: hacktober-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      # The mysql image will run any .sql script you put here on up
      - ./docker-compose/db/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    networks:
      - hacktober

  nginx:
    image: nginx:alpine
    container_name: hacktober-nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    ports:
      - 8000:80
    depends_on:
      - app
    networks:
      - hacktober

networks:
  hacktober:
    driver: bridge

# Specify the named volumes used above
volumes:
  empty:
