version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: erikaheidi/hacktober-board
    container_name: hacktober-app
    restart: unless-stopped
    working_dir: /var/www/
    networks:
      - hacktober
    volumes:
      - ./:/var/www

  db:
    image: mysql:5.7.22
    container_name: hacktober-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - hacktober

  nginx:
    image: nginx:alpine
    container_name: hacktober-nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    ports:
      - 8000:80
    networks:
      - hacktober

networks:
  hacktober:
    driver: bridge
