
# You can copy this Dockerfile.example to Dockerfile to add configuration
# or packages or anything else to your webimage
ARG BASE_IMAGE=drud/ddev-webserver:v1.11.0
FROM $BASE_IMAGE
RUN npm install --global gulp-cli
