
# You can copy this Dockerfile.example to Dockerfile to add configuration
# or packages or anything else to your dbimage
ARG BASE_IMAGE=drud/ddev-dbserver:v1.11.0-10.2
FROM $BASE_IMAGE
RUN echo "Built from drud/ddev-dbserver:v1.11.0-10.2" >/var/tmp/built-from.txt
